
name: Deploy WordPress to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5
        with:
          ssh-private-key: ${{ secrets.ec2_private_key }}

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.233.95.101 'cd /var/www/html/wordpress && git pull origin main'
